import type { MenuItem } from '@/lib/types';

export const menuItems: MenuItem[] = [
  { id: '1', name: 'Apricot Delight', category: 'Swiss Delights Specials', description: '', price: 178, image: '', available: true },
  { id: '2', name: 'Bombay Vadapav', category: 'Swiss Delights Specials', description: '', price: 99, image: '', available: true },
  { id: '3', name: 'Chicken Sub Sandwich', category: 'Swiss Delights Specials', description: '', price: 169, image: '', available: true },
  { id: '4', name: 'Choco Cashew Crunch', category: 'Swiss Delights Specials', description: '', price: 189, image: '', available: true },
  { id: '5', name: 'Veg Sub Sandwich', category: 'Swiss Delights Specials', description: '', price: 160, image: '', available: true },
  { id: '6', name: 'Apple Juice', category: 'Beverages', description: '', price: 169, image: '', available: true },
  { id: '7', name: 'Diet Coke', category: 'Beverages', description: '', price: 40, image: '', available: true },
  { id: '8', name: 'Monster Tins', category: 'Beverages', description: '', price: 125, image: '', available: true },
  { id: '9', name: 'Pineapple Juice', category: 'Beverages', description: '', price: 169, image: '', available: true },
  { id: '10', name: 'Pomegranate Juice', category: 'Beverages', description: '', price: 169, image: '', available: true },
  { id: '11', name: 'Pulpy Orange 1L', category: 'Beverages', description: '', price: 90, image: '', available: true },
  { id: '12', name: 'Red Bull', category: 'Beverages', description: '', price: 125, image: '', available: true },
  { id: '13', name: 'Thumpsup 1L', category: 'Beverages', description: '', price: 50, image: '', available: true },
  { id: '14', name: 'Thumpsup Tins', category: 'Beverages', description: '', price: 40, image: '', available: true },
  { id: '15', name: 'Watermelon Juice', category: 'Beverages', description: '', price: 169, image: '', available: true },
  { id: '16', name: 'Water 1L', category: 'Beverages', description: '', price: 18, image: '', available: true },
  { id: '17', name: 'Water bottel 500ml', category: 'Beverages', description: '', price: 9, image: '', available: true },
  { id: '18', name: 'Water bottle 1L', category: 'Beverages', description: '', price: 18, image: '', available: true },
  { id: '19', name: 'Brown Bread 450G', category: 'Breads', description: '', price: 49, image: '', available: true },
  { id: '20', name: 'Burger Buns', category: 'Breads', description: '', price: 49, image: '', available: true },
  { id: '21', name: 'Garlic Leaf Bread', category: 'Breads', description: '', price: 69, image: '', available: true },
  { id: '22', name: 'Milk Bread 450G', category: 'Breads', description: '', price: 49, image: '', available: true },
  { id: '23', name: 'Multigrain Bread', category: 'Breads', description: '', price: 59, image: '', available: true },
  { id: '24', name: 'Pav Bun 40G', category: 'Breads', description: '', price: 49, image: '', available: true },
  { id: '25', name: 'Curd Rice', category: 'Biryani & Rice', description: '', price: 238, image: '', available: true },
  { id: '26', name: 'Mini Chicken Dum Biryani', category: 'Biryani & Rice', description: '', price: 247, image: '', available: true },
  { id: '27', name: 'Sambar Rice', category: 'Biryani & Rice', description: '', price: 195, image: '', available: true },
  { id: '28', name: 'Special Chicken Biryani', category: 'Biryani & Rice', description: '', price: 262, image: '', available: true },
  { id: '29', name: 'Brownie', category: 'Brownie', description: '', price: 99, image: '', available: true },
  { id: '30', name: 'Nutella Brownie', category: 'Brownie', description: '', price: 99, image: '', available: true },
  { id: '31', name: 'Assorted mini burgers', category: 'Burgers and Sandwiches', description: '', price: 229, image: '', available: true },
  { id: '32', name: 'Chicken Grill Sandwich', category: 'Burgers and Sandwiches', description: '', price: 219, image: '', available: true },
  { id: '33', name: 'Crispy Chicken Burger', category: 'Burgers and Sandwiches', description: '', price: 228, image: '', available: true },
  { id: '34', name: 'Paneer Grill Sandwich', category: 'Burgers and Sandwiches', description: '', price: 199, image: '', available: true },
  { id: '35', name: 'Veg Grill Sandwich', category: 'Burgers and Sandwiches', description: '', price: 189, image: '', available: true },
  { id: '36', name: 'Veg Sub Sandwich', category: 'Burgers and Sandwiches', description: '', price: 160, image: '', available: true },
  { id: '37', name: 'Almond Mocha Rochear Cake 1KG', category: 'Cakes', description: '', price: 899, image: '', available: true },
  { id: '38', name: 'Almond Mocha Rochear Cake 500G', category: 'Cakes', description: '', price: 499, image: '', available: true },
  { id: '39', name: 'Belgium Butter Scotch Cake 1KG', category: 'Cakes', description: '', price: 899, image: '', available: true },
  { id: '40', name: 'Belgium Butter Scotch Cake 500G', category: 'Cakes', description: '', price: 499, image: '', available: true },
  { id: '41', name: 'Black Forest Cake 1KG', category: 'Cakes', description: '', price: 899, image: '', available: true },
  { id: '42', name: 'Black Forest Cake 500G', category: 'Cakes', description: '', price: 499, image: '', available: true },
  { id: '43', name: 'Butter Scotch Cake 1KG', category: 'Cakes', description: '', price: 899, image: '', available: true },
  { id: '44', name: 'Butter Scotch Cake 500G', category: 'Cakes', description: '', price: 499, image: '', available: true },
  { id: '45', name: 'Choco Vanilla Cake 1KG', category: 'Cakes', description: '', price: 1099, image: '', available: true },
  { id: '46', name: 'Choco Vanilla Cake 500G', category: 'Cakes', description: '', price: 699, image: '', available: true },
  { id: '47', name: 'Chocochip Cake 500gm', category: 'Cakes', description: '', price: 799, image: '', available: true },
  { id: '48', name: 'Chocolate Overload Cake 1kg', category: 'Cakes', description: '', price: 1299, image: '', available: true },
  { id: '49', name: 'Chocolate Truffle Cake 1KG', category: 'Cakes', description: '', price: 1099, image: '', available: true },
  { id: '50', name: 'Chocolate Truffle Cake 500G', category: 'Cakes', description: '', price: 699, image: '', available: true },
  { id: '51', name: 'Hazelnut Cake 1kg', category: 'Cakes', description: '', price: 1299, image: '', available: true },
  { id: '52', name: 'Pineapple Cake 500G', category: 'Cakes', description: '', price: 499, image: '', available: true },
  { id: '53', name: 'Chocolate Cube Cake', category: 'Cheese Cake', description: '', price: 189, image: '', available: true },
  { id: '54', name: 'Chocolate Mousse Sandwich', category: 'Cheese Cake', description: '', price: 179, image: '', available: true },
  { id: '55', name: 'Red Velvet Cheese Cake', category: 'Cheese Cake', description: '', price: 179, image: '', available: true },
  { id: '56', name: 'Tiramisu Jar', category: 'Cheese Cake', description: '', price: 169, image: '', available: true },
  { id: '57', name: 'Tripel Chocolate Cheese Cake', category: 'Cheese Cake', description: '', price: 179, image: '', available: true },
  { id: '58', name: 'Triple Chocolate Cheese Cake', category: 'Cheese Cake', description: '', price: 179, image: '', available: true },
  { id: '59', name: 'chocolate mousse jar', category: 'Cheese Cake', description: '', price: 189, image: '', available: true },
  { id: '60', name: 'Americano 210ml', category: 'Coffees', description: '', price: 89, image: '', available: true },
  { id: '61', name: 'Cafe Latte 210ml', category: 'Coffees', description: '', price: 149, image: '', available: true },
  { id: '62', name: 'Cafe Mocha 210ml', category: 'Coffees', description: '', price: 119, image: '', available: true },
  { id: '63', name: 'Cappuccino 210ml', category: 'Coffees', description: '', price: 119, image: '', available: true },
  { id: '64', name: 'Cold Coffee', category: 'Coffees', description: '', price: 219, image: '', available: true },
  { id: '65', name: 'Espresso 45ml', category: 'Coffees', description: '', price: 79, image: '', available: true },
  { id: '66', name: 'Iced Caramel Coffee 300ml', category: 'Coffees', description: '', price: 199, image: '', available: true },
  { id: '67', name: 'Macchiato 50ml', category: 'Coffees', description: '', price: 119, image: '', available: true },
  { id: '68', name: 'Spanish Latte 210ml', category: 'Coffees', description: '', price: 149, available: true },
  { id: '69', name: 'Cortado 90ml', category: 'Coffees', description: '', price: 119, image: '', available: true },
  { id: '70', name: 'Ajwain Biscuits', category: 'Cookies', description: '', price: 159, image: '', available: true },
  { id: '71', name: 'Cashew & Oats Biscuits', category: 'Cookies', description: '', price: 229, image: '', available: true },
  { id: '72', name: 'Caster Sugar Biscuits 250gm', category: 'Cookies', description: '', price: 169, image: '', available: true },
  { id: '73', name: 'Chocochip Cookies', category: 'Cookies', description: '', price: 199, image: '', available: true },
  { id: '74', name: 'Coconut Biscuits', category: 'Cookies', description: '', price: 229, image: '', available: true },
  { id: '75', name: 'Custard Biscuits', category: 'Cookies', description: '', price: 169, image: '', available: true },
  { id: '76', name: 'Fruit Biscuits', category: 'Cookies', description: '', price: 249, image: '', available: true },
  { id: '77', name: 'Ghee Wheat Biscuits', category: 'Cookies', description: '', price: 199, image: '', available: true },
  { id: '78', name: 'Lotus Biscoff Cookies (1Pc)', category: 'Cookies', description: '', price: 79, image: '', available: true },
  { id: '79', name: 'Nutella Cookies (1Pc)', category: 'Cookies', description: '', price: 89, image: '', available: true },
  { id: '80', name: 'Oats Biscuits 250gm', category: 'Cookies', description: '', price: 229, image: '', available: true },
  { id: '81', name: 'Osmania Biscuits', category: 'Cookies', description: '', price: 189, image: '', available: true },
  { id: '82', name: 'Ragi Cookies 250gm', category: 'Cookies', description: '', price: 259, image: '', available: true },
  { id: '83', name: 'Snow Cookies', category: 'Cookies', description: '', price: 210, image: '', available: true },
  { id: '84', name: 'Butter Croissant', category: 'Croissant', description: '', price: 109, image: '', available: true },
  { id: '85', name: 'Chocolate Croissant', category: 'Croissant', description: '', price: 139, image: '', available: true },
  { id: '86', name: 'Mini Croissant', category: 'Croissant', description: '', price: 89, image: '', available: true },
  { id: '87', name: 'Berry Cup Cake', category: 'Cup Cakes', description: '', price: 69, image: '', available: true },
  { id: '88', name: 'Biscoff Cup Cake', category: 'Cup Cakes', description: '', price: 79, image: '', available: true },
  { id: '89', name: 'Chocolate Cup Cake', category: 'Cup Cakes', description: '', price: 79, image: '', available: true },
  { id: '90', name: 'Vanilla Cup Cake', category: 'Cup Cakes', description: '', price: 59, image: '', available: true },
  { id: '91', name: 'Doughnuts', category: 'Doughnuts', description: '', price: 89, image: '', available: true },
  { id: '92', name: 'Caramel Frappe', category: 'Frappes', description: '', price: 199, image: '', available: true },
  { id: '93', name: 'Coffee Frappe', category: 'Frappes', description: '', price: 199, image: '', available: true },
  { id: '94', name: 'Hazelnut Frappe', category: 'Frappes', description: '', price: 199, image: '', available: true },
  { id: '95', name: 'Mocha Frappe', category: 'Frappes', description: '', price: 199, image: '', available: true },
  { id: '96', name: 'Vanilla Frappe', category: 'Frappes', description: '', price: 199, image: '', available: true },
  { id: '97', name: 'Chocolate Muffin', category: 'Muffins', description: '', price: 40, image: '', available: true },
  { id: '98', name: 'Vanilla Muffins', category: 'Muffins', description: '', price: 40, image: '', available: true },
  { id: '99', name: 'Banana Chips 250gm', category: 'Namkeen', description: '', price: 159, image: '', available: true },
  { id: '100', name: 'Besan Palli 250gm', category: 'Namkeen', description: '', price: 169, image: '', available: true },
  { id: '101', name: 'Chakodi 250gm', category: 'Namkeen', description: '', price: 129, image: '', available: true },
  { id: '102', name: 'Cornflakes Mixture 250gm', category: 'Namkeen', description: '', price: 149, image: '', available: true },
  { id: '103', name: 'Navratan Mixture 250gm', category: 'Namkeen', description: '', price: 189, image: '', available: true },
  { id: '104', name: 'Potato Chips Spicy 300gm', category: 'Namkeen', description: '', price: 199, image: '', available: true },
  { id: '105', name: 'Ragi Mixture 250gm', category: 'Namkeen', description: '', price: 199, image: '', available: true },
  { id: '106', name: 'Salted Potato Chips 300gm', category: 'Namkeen', description: '', price: 199, image: '', available: true },
  { id: '107', name: 'Tomato Murukulu 250gm', category: 'Namkeen', description: '', price: 159, image: '', available: true },
  { id: '108', name: 'Birthday Caps', category: 'Party Items', description: '', price: 20, image: '', available: true },
  { id: '109', name: 'Number Candles', category: 'Party Items', description: '', price: 59, image: '', available: true },
  { id: '110', name: 'Party Poppers', category: 'Party Items', description: '', price: 99, image: '', available: true },
  { id: '111', name: 'Sparkel', category: 'Party Items', description: '', price: 25, image: '', available: true },
  { id: '112', name: 'Creamy Alfredo Non Veg Pasta (Penne/Spaghetti)', category: 'Pasta\'s', description: '', price: 299, image: '', available: true },
  { id: '113', name: 'Creamy Alfredo Veg Pasta (Penne/Spaghetti)', category: 'Pasta\'s', description: '', price: 248, image: '', available: true },
  { id: '114', name: 'Tangy Arrabita Non Veg Pasta (Penne/Spaghetti)', category: 'Pasta\'s', description: '', price: 259, image: '', available: true },
  { id: '115', name: 'Tangy Arrabita Veg Pasta (Penne/Spaghetti)', category: 'Pasta\'s', description: '', price: 228, image: '', available: true },
  { id: '116', name: 'Almond Mocha Rochear Pastry', category: 'Pastry', description: '', price: 99, image: '', available: true },
  { id: '117', name: 'Belgium Butter Scotch Pastry', category: 'Pastry', description: '', price: 99, image: '', available: true },
  { id: '118', name: 'Butterscotch Pastry', category: 'Pastry', description: '', price: 89, image: '', available: true },
  { id: '119', name: 'Choco Chip Pastry', category: 'Pastry', description: '', price: 99, image: '', available: true },
  { id: '120', name: 'Chocolate Truffle Pastry', category: 'Pastry', description: '', price: 120, image: '', available: true },
  { id: '121', name: 'Chocovanilla Pastry', category: 'Pastry', description: '', price: 99, image: '', available: true },
  { id: '122', name: 'Pineapple Pastry', category: 'Pastry', description: '', price: 89, image: '', available: true },
  { id: '123', name: 'Red Velvet Pastry', category: 'Pastry', description: '', price: 99, image: '', available: true },
  { id: '124', name: 'Chicken Puff', category: 'Puff\'s', description: '', price: 59, image: '', available: true },
  { id: '125', name: 'Egg Puff', category: 'Puff\'s', description: '', price: 49, image: '', available: true },
  { id: '126', name: 'Veg Puff', category: 'Puff\'s', description: '', price: 39, image: '', available: true },
  { id: '127', name: 'Hot Chocolate', category: 'Refreshers', description: '', price: 149, image: '', available: true },
  { id: '128', name: 'Lemonade', category: 'Refreshers', description: '', price: 129, image: '', available: true },
  { id: '129', name: 'Virgin Mojito', category: 'Refreshers', description: '', price: 129, image: '', available: true },
  { id: '130', name: 'Chicken Fried Rice With Chicken Manchurian Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 210, image: '', available: true },
  { id: '131', name: 'Chicken Fried Rice With Schezwan Chicken Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 210, image: '', available: true },
  { id: '132', name: 'Chicken Schezwan Noodles With Schezwan Chicken Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 210, image: '', available: true },
  { id: '133', name: 'Chicken Singapore Noodles Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 210, image: '', available: true },
  { id: '134', name: 'Chilly Garlic Noodles With Chilly Chicken Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 210, image: '', available: true },
  { id: '135', name: 'Egg Fried Rice With Chilli Chicken', category: 'Rice Bowl\'s & Noodles', description: '', price: 199, image: '', available: true },
  { id: '136', name: 'Street Style Chicken Fried Rice Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 210, image: '', available: true },
  { id: '137', name: 'Street Style Veg Fried Rice Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 189, image: '', available: true },
  { id: '138', name: 'Veg Fried Rice With Chilli Paneer Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 189, image: '', available: true },
  { id: '139', name: 'Veg Fried Rice With Veg Manchurian Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 189, image: '', available: true },
  { id: '140', name: 'Veg Hakka Noodles With Chilli Paneer Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 189, image: '', available: true },
  { id: '141', name: 'Veg Hakka Noodles With Veg Manchurian Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 189, image: '', available: true },
  { id: '142', name: 'Veg Singapore Noodles Wet', category: 'Rice Bowl\'s & Noodles', description: '', price: 189, image: '', available: true },
  { id: '143', name: 'Blueberry Shake', category: 'Shakes', description: '', price: 179, image: '', available: true },
  { id: '144', name: 'Brownie Shake', category: 'Shakes', description: '', price: 219, image: '', available: true },
  { id: '145', name: 'Chocolate Shake', category: 'Shakes', description: '', price: 179, image: '', available: true },
  { id: '146', name: 'Coffee Shake', category: 'Shakes', description: '', price: 189, image: '', available: true },
  { id: '147', name: 'Kitkat Shake', category: 'Shakes', description: '', price: 179, image: '', available: true },
  { id: '148', name: 'Mix Berry Shake', category: 'Shakes', description: '', price: 179, image: '', available: true },
  { id: '149', name: 'Nutella Brownie Shake', category: 'Shakes', description: '', price: 239, image: '', available: true },
  { id: '150', name: 'Oreo Shake', category: 'Shakes', description: '', price: 179, image: '', available: true },
  { id: '151', name: 'Vanilla shake', category: 'Shakes', description: '', price: 179, image: '', available: true },
  { id: '152', name: 'Chicken 65', category: 'Starters', description: '', price: 189, image: '', available: true },
  { id: '153', name: 'Chicken Drumsticks (2 Pieces)', category: 'Starters', description: '', price: 129, image: '', available: true },
  { id: '154', name: 'Chilli Chicken', category: 'Starters', description: '', price: 189, image: '', available: true },
  { id: '155', name: 'Chilli Garlic Potato Pops (12 Pieces)', category: 'Starters', description: '', price: 149, image: '', available: true },
  { id: '156', name: 'Chilli Paneer', category: 'Starters', description: '', price: 179, image: '', available: true },
  { id: '157', name: 'Crispy Onion Rings (7 Pieces)', category: 'Starters', description: '', price: 199, image: '', available: true },
  { id: '158', name: 'Crunchy Chicken (7 Pieces)', category: 'Starters', description: '', price: 210, image: '', available: true },
  { id: '159', name: 'Peri-peri Fries', category: 'Starters', description: '', price: 159, image: '', available: true },
  { id: '160', name: 'Potato Smiles (8 Pieces)', category: 'Starters', description: '', price: 119, image: '', available: true },
  { id: '161', name: 'Salted Fries', category: 'Starters', description: '', price: 119, image: '', available: true },
  { id: '162', name: 'Veg Manchuria', category: 'Starters', description: '', price: 159, image: '', available: true },
  { id: '163', name: 'Marble Tea Cake', category: 'Tea Cake', description: '', price: 49, image: '', available: true },
  { id: '164', name: 'Vanilla Tea Cake', category: 'Tea Cake', description: '', price: 49, image: '', available: true }
];